language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $db57924486cda2d1e8547f02b99edf70592dea76
 local_dir: dist
 on:
   branch: master
